### PR TITLE
feat: add `binaryType` parameter to WebSocket class

### PR DESCRIPTION
**Pull request by mytja**
## Status
**DONE**

## Description
Greetings,
I really like this project. It's just so simple to use and painless. That's why I'm thanking you for your time taken to maintain the project. Unfortunately it wasn't working on Flutter for the Web, as I was using Protobuf and consequently ran into issues with JavaScript Blob to List<int> (bytearray) conversion. This fix adds another parameter to the class, which [is ran](https://api.dart.dev/stable/2.19.3/dart-html/WebSocket-class.html) by the `dart:html` WebSocket class and with the help of it, I'm able to set the `binaryType` to `arraybuffer`, per [this source](https://stackoverflow.com/questions/18578539/convert-blob-to-listint) and it successfully works with Protobuf.

Before adding the flag/parameter
image

After adding the flag and setting it to `arraybuffer`
image

## Type of Change
- [x] ✨ New feature (non-breaking change which adds functionality)
- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [x] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

**Comment by felangel** [comment]
@mytja thanks so much for the positive feedback and for contributing! Looks like ci is failing due to an analysis warning. Are you able to quickly resolve that? If not let me know and I’m happy to help 👍

**Comment by mytja** [comment]
Sure, I can do that.

**Comment by mytja** [comment]
This should pass the analysis.

**Review by felangel — APPROVED** [review]
LGTM thanks so much for the contribution! 💯

**Pull request merged**
